name: Build Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release
  
jobs:
  build:
    runs-on: windows-latest

    steps:
#      - uses: msys2/setup-msys2@v2
#        with:
#            install: mingw-w64-x86_64-toolchain
#            msystem: mingw64
#            release: false
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.8.3'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_mingw'
        dir: '${{github.workspace}}/qt/'
        tools: 'tools_ninja tools_cmake tools_mingw1310'
        install-deps: 'false'
        cache: 'true'

    - name: Checkout Project
      uses: actions/checkout@v4.2.2
      
    # - name: Build Project
    #   uses: threeal/cmake-action@v2.1.0
    
    - name: Configure CMake
      env:
        CMAKE_PREFIX_PATH: ${{env.QT_ROOT_DIR}}
        CMAKE_C_COMPILER: ${{env.IQTA_TOOLS}}\mingw1310_64\bin\gcc.exe
        CMAKE_CXX_COMPILER: ${{env.IQTA_TOOLS}}\mingw1310_64\bin\g++.exe
        Qt6_DIR: ${{env.QT_ROOT_DIR}}\lib\cmake\Qt6
      run: | 
        cd ${{github.workspace}}/src
        cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_CXX_COMPILER=${{env.CMAKE_CXX_COMPILER}} -DCMAKE_C_COMPILER=${{env.CMAKE_C_COMPILER}} -G "Ninja" -B '${{github.workspace}}/build'
      
    - name: Build
      run: cmake --build '${{github.workspace}}'/build --target RePr
